### ISSUE TITLE
Phone app issue

### ISSUE THREAD

**Issue by Chrismtl7** [Windkracht8/RugbyRefereeWatch#1]
I'm not sure if this is the place, but I have an issue with the companion app that is installed on my Pixel 4. I keep getting the error "You need to install the Samsung Accessory Service first". I have this installed since it's not an issue for any of my other apps and I have tried uninstalling and re-installing both the accessory service app and your app to no avail. I think that the watch app is amazing and does everything I could want, I just can't access my match reports on my phone.

**Comment by Windkracht8** [comment]
Hi Chrismtl7,
You got the right place. Can I check if you have the same package? This is the Samsung Accesory Service I am expecting: https://play.google.com/store/apps/details?id=com.samsung.accessory
Is that the one you have installed? If so it might be resolved by force closing Rugby Referee Watch and opening it again after making sure the app above is installed.

**Comment by Chrismtl7** [comment]
Hey Windkracht8,

Thanks for the quick reply!

Yup, that's the one I have installed. I've tried uninstalling it and reinstalling it. I even tried again today to uninstall and reinstall your phone app. I've attached a screenshot of the message I'm getting in case it helps. I've also force closed all the apps and restarted my phone and watch. 

![Screenshot_20201222-193115](https://user-images.githubusercontent.com/76487647/102945697-84db3200-448c-11eb-9cd7-c97f79c1e9af.png)

**Comment by Windkracht8** [comment]
It seems that Samsung does not support Android 11 yet for the type of app I have created. Even after I have updated all I can I cannot make my app work on an emulator for Pixel 4 with Android 11.
Sorry to say we will have to wait for Samsung to update their library to support this. When they do, I will be happy to update my app.

**Comment by Chrismtl7** [comment]
No problem and thank you for trying! I really do love the watch app and it very much does the job I need. Looking forward to Samsung hopefully updating their systems.

**Comment by Windkracht8** [comment]
Hi again,
I think I found and fixed the problem. Look for a new version 1.4.2 in the Galaxy store. This update will soon also be available in the Play store.

**Comment by Chrismtl7** [comment]
Awesome! I'll look out for the update and let you know how it goes. Thanks a lot!
